-- ================================================================
-- CSSBERLIN E-COMMERCE DATABASE UPDATE
-- Generated by Claude AI - Vibecoding Approach
-- ================================================================
-- This script will:
-- 1. Create new tables: Color, Size, Brand, Material
-- 2. Add foreign keys to Product table
-- 3. Keep existing data safe (no data loss)
-- ================================================================

-- Step 1: Create Color Table
CREATE TABLE IF NOT EXISTS "Color" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    "name" TEXT UNIQUE NOT NULL,
    "hexCode" TEXT
);

-- Step 2: Create Size Table
CREATE TABLE IF NOT EXISTS "Size" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    "name" TEXT UNIQUE NOT NULL
);

-- Step 3: Create Brand Table
CREATE TABLE IF NOT EXISTS "Brand" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    "name" TEXT UNIQUE NOT NULL
);

-- Step 4: Create Material Table
CREATE TABLE IF NOT EXISTS "Material" (
    "id" TEXT PRIMARY KEY DEFAULT gen_random_uuid()::TEXT,
    "name" TEXT UNIQUE NOT NULL
);

-- Step 5: Add new columns to Product table (if not exists)
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "colorId" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sizeId" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "brandId" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "materialId" TEXT;

-- Step 6: Create Foreign Key Constraints
ALTER TABLE "Product" DROP CONSTRAINT IF EXISTS "Product_colorId_fkey";
ALTER TABLE "Product" DROP CONSTRAINT IF EXISTS "Product_sizeId_fkey";
ALTER TABLE "Product" DROP CONSTRAINT IF EXISTS "Product_brandId_fkey";
ALTER TABLE "Product" DROP CONSTRAINT IF EXISTS "Product_materialId_fkey";

ALTER TABLE "Product"
    ADD CONSTRAINT "Product_colorId_fkey"
    FOREIGN KEY ("colorId") REFERENCES "Color"("id") ON DELETE SET NULL;

ALTER TABLE "Product"
    ADD CONSTRAINT "Product_sizeId_fkey"
    FOREIGN KEY ("sizeId") REFERENCES "Size"("id") ON DELETE SET NULL;

ALTER TABLE "Product"
    ADD CONSTRAINT "Product_brandId_fkey"
    FOREIGN KEY ("brandId") REFERENCES "Brand"("id") ON DELETE SET NULL;

ALTER TABLE "Product"
    ADD CONSTRAINT "Product_materialId_fkey"
    FOREIGN KEY ("materialId") REFERENCES "Material"("id") ON DELETE SET NULL;

-- ================================================================
-- IMPORTANT NOTES:
-- ================================================================
-- 1. Old columns (brand, size, color, material as TEXT) are kept
-- 2. New columns (brandId, sizeId, colorId, materialId) are nullable
-- 3. You can migrate data later manually or with a script
-- 4. No data loss will occur
-- ================================================================

-- Optional: Drop old TEXT columns (UNCOMMENT IF YOU WANT TO REMOVE OLD COLUMNS)
-- WARNING: This will delete existing brand/size/color/material data!
-- ALTER TABLE "Product" DROP COLUMN IF EXISTS "brand";
-- ALTER TABLE "Product" DROP COLUMN IF EXISTS "size";
-- ALTER TABLE "Product" DROP COLUMN IF EXISTS "color";
-- ALTER TABLE "Product" DROP COLUMN IF EXISTS "material";

-- Success message
SELECT 'Database updated successfully! ✅' AS status;
